### PR TITLE
Removing openssl

### PR DESCRIPTION
**Pull request by hermabe**
Keeping with the tradition of deleting stuff and seeing what happens, this PR removes openssl and with it all the assembly. 
This comes at the cost of removing the shasum foreign. That is, `128!:6` does no longer work and gives a `domain error`.

I think this cost is ok, given that we are able to delete 90 000 lines of assembly.

J foreign docs: https://code.jsoftware.com/wiki/Vocabulary/bangco, https://code.jsoftware.com/wiki/Vocabulary/Foreigns#m128

The test for `128!:6` (`g128x6.ijs`) and one test using it (`g640.ijs`) is also removed.

### CODE REVIEW

**Comment by codereport** [comment]
Once CI passes (I will get unit tests hooked up to CI as well), will definitely merge this! Deleting ~100k LOC is :fire:

**Comment by hermabe** [comment]
Linux builds, getting linker error on mac:
```
Undefined symbols for architecture x86_64:
  "_base64_decode", referenced from:
      _jtfrombase64 in xcrc.c.o
  "_base64_encode", referenced from:
      _jttobase64 in xcrc.c.o
```
Some stuff in base64 was deleted in the first stream I think, I'll look into it.

**Comment by hermabe** [comment]
I was a bit eager when deleting linker flags. Surprised it actually worked on Linux at all.

**Comment by hermabe** [comment]
Results from running tests locally:
```
jsource/build$ ctest -C Debug
...

96% tests passed, 15 tests failed out of 404

Total Test time (real) = 596.59 sec

The following tests FAILED:
        117 - g210a (SEGFAULT)
        122 - g221 (Failed)
        136 - g300 (Failed)
        156 - g331 (SEGFAULT)
        225 - g5x30 (Failed)
        233 - g602 (Failed)
        255 - g9x40 (Failed)
        270 - gebar (Failed)
        301 - gmmf (Failed)
        302 - gmmf1s (Failed)
        303 - gmmf1u (Failed)
        304 - gmmf1w (Failed)
        390 - gstack (SEGFAULT)
        395 - gu (Failed)
        396 - gu0 (Failed)
```

**Review by codereport — APPROVED** [review]
:fire: :fire: :fire: :wave: ~100K LOC

**Pull request merged**
