### PR TITLE
attempt to make subdirectories for Adverbs, Conjunctions and Verbs.

### PR DESCRIPTION
**Pull request by Sebanisu**
I think this might be working. I wanted the CI to run on it. There are probably bugs in my cmake to work out. Though I built it and it didn't error. So maybe we'll be lucky and things work.

I noticed that the words were in comments at the top of files. So using things like:
`find . -maxdepth 1   -type f -exec grep -l -H 'Verbs' {} \;`
I copied the output into excel and used a formula:
`="git mv -v "&[@filename]&" "&$F$1` where `$F$1` is a directory.
So I ended up with something like:
`git mv -v ./crc32c.c ./verbs`
So I used the commands moved the files then cleaned up the CMakeLists.

There might be stragglers like files that are only included by Adverbs, Conjunctions and Verbs should probably go into those directories. Or I may of moved things that didn't need to be.

Hopefully resolves: https://github.com/codereport/jsource/issues/27

### CODE REVIEW

**Comment by Sebanisu** [comment]
Okay so it looks like include_target_directories isn't working for verbs. Let me double check that CMakeLists.txt

**Comment by Sebanisu** [comment]
Hmm oh I see something the verbs (v0.c) are including j.h So maybe j.h is required by all the libs. So it'll probably need it's own library.

**Comment by Sebanisu** [comment]
So I made a 4th library that is to be depended on by the Adverbs, Conjunctions and Verbs. Though I got them to build. It's failing on linking.
```
[  2%] Built target tsdll
[  6%] Built target j-base64
[  6%] Built target lib_j_parent
[ 16%] Built target lib_adverbs
[ 21%] Built target lib_conjunction
[ 45%] Built target lib_verbs
[ 46%] Linking C shared library libj.so
/usr/bin/ld: cannot find -llib_conjunctions
```
This confuses me a bit these is probably something off on my cmakelists.txt. Though it's basically building the library's then cannot find them.

**Comment by Sebanisu** [comment]
Turned out I was putting s at the end in one cmakelists.txt and not the other. And then it's forcing me to make my new libraries SHARED instead of STATIC. Because the code uses symbols that can't be in a STATIC library. And now it's giving undefined references because exten cannot find functions defined in another file somewhere. So I'll probably adjust this back to one library that knows where the files are and use INTERFACE libraries to simplify the include path. INTERFACES don't care where the files are they just pass settings around and such.

**Comment by Sebanisu** [comment]
I'm gonna do a fresh pull from main. I think the new method is good. I'm getting errors. So I wanna do a fresh pull from main and do one group at a time. As it's getting hard to find where I messed up heh.

**Comment by codereport** [comment]
Looking forward to the new PR :fire: This will be awesome if we can get it in! :pray:

**Pull request closed without merging**
