### PR TITLE
Split folder adverbs. Also conjunctions and verbs!

### PR DESCRIPTION
**Pull request by Sebanisu**
Due to my previous attempt going up in smoke I'm doing like one of these at a time. :D

The ` target_include_directories` is working. All these files will look in `./jsrc` as if they were in that folder.
So you to include `./jsrc/adverbs/a.h` from `./jsrc/j.h` you need `#include “adverbs/a.h”`.
But to go the other way you don’t need to change it. `./jsrc/j.h` from `./jsrc/adverbs/a.h` is just `#include “j.h”`

You can have multiple directories in `target_include_directories` but it seems to break when you have directories in the same tree like `./jsrc/adverbs` and `./jsrc`. But something like `./jsrc/adverbs` and `./jsrc/misc` should work.

Resolves https://github.com/codereport/jsource/issues/27

### CODE REVIEW

**Comment by Sebanisu** [comment]
After doing the adverbs. I also conjunctions and verbs in other branches. Since this one wasn't merged I went ahead and pushed the commits from the other branches into this one. So this should take care of all 3 of those folders now. I'll update the title.

**Comment by Sebanisu** [comment]
Oh there is a conflict.

**Comment by codereport** [comment]
Conflicts :upside_down_face:  Are you able to resolve or redo? I will hold off on merging PRs till then.

**Comment by Sebanisu** [comment]
I rebased the branch. That seemed to get rid of the merge conflict.

**Review by codereport — APPROVED** [review]
THIS IS AWESOME! Also `git` is amazing! :fire: :rocket: :pray:

**Pull request merged**
