### PR TITLE
Centered-title-and-badges-in README.md

### LINKED ISSUE #10: Center README.md Title and badges by converting to HTML with <center> tags
Currently, the title and badges in the README.md are left aligned. It would look nicer if it was centered, but this requires switching from markdown to HTML.

### PR DESCRIPTION
**Pull request by 96RadhikaJadhav**
This PR will resolves #10 .

### CODE REVIEW

**Review by codereport — CHANGES_REQUESTED** [review]
This is a great start :fire:! However, markdown can't be rendered in HTML (see how it renders below). Ideally, we want the README.md to render the same way it currently is, just center aligned (which you can't do in markdown which is why we need HTML). So the markdown actually needs to be translated into HTML. If you search online for Github badges in HTML, you should be able to find the equivalent code to the existing markdown.

image

**Comment by 96RadhikaJadhav** [comment]
@codereport  Please review my recent commit. Title and badges are centered now. Please let me know if any other changes required.

**Review by codereport — CHANGES_REQUESTED** [review]
Looks great! Thanks :pray: Only thing left is for merge conflicts to be resolved.

**Review by codereport — APPROVED** [review]
I fixed the merge conflicts :slightly_smiling_face:

**Comment by 96RadhikaJadhav** [comment]
> I fixed the merge conflicts 🙂

@codereport  I was working on merge conflicts but was facing issue. It would be a great help to me if you could mention the step here that you followed to resolve it. Thanks in advance 🙂.

**Comment by codereport** [comment]
@96RadhikaJadhav These are the steps:
1. `git checkout main`
2. `git pull origin main`
3. `git checkout centering-title-and-badges`
4. `git merge main`
5. Then I opened VSCode and carefully resolved the merge conflicts. There were quite a few updates to the `README.md` so I figured it might be easier for me to do it. 

Thanks for doing the heavy lifting on this PR :pray:

**Comment by 96RadhikaJadhav** [comment]
> @96RadhikaJadhav These are the steps:
> 
> 1. `git checkout main`
> 2. `git pull origin main`
> 3. `git checkout centering-title-and-badges`
> 4. `git merge main`
> 5. Then I opened VSCode and carefully resolved the merge conflicts. There were quite a few updates to the `README.md` so I figured it might be easier for me to do it.
> 
> Thanks for doing the heavy lifting on this PR 🙏

It's all my pleasure. Thank You 🙂.

**Pull request merged**
